stages:
  - build
  - test
  - sonar

variables:
  SONAR_USER_HOME: "${CI_PROJECT_DIR}/.sonar"  # Définit l'emplacement du cache de l'analyse
  GIT_DEPTH: "0"  # Indique à Git de récupérer tous les branches pour SonarQube

sonarcloud-check:
  image: sonarsource/sonar-scanner-cli:latest
  stage: sonar
  script:
    - sonar-scanner \
        -Dsonar.projectKey="votre_project_key" \
        -Dsonar.organization="votre_organisation" \
        -Dsonar.host.url="https://sonarcloud.io" \
        -Dsonar.login="${SONAR_TOKEN}"  # Assurez-vous que cette variable est définie dans GitLab CI/CD
  only:
    - master
    - develop
    - merge_requests  # Exécute l'analyse pour les MR

cache:
  paths:
    - .sonar/cache  # Cache des résultats pour optimiser les prochaines analyses
