version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel_app
    environment:
      - APP_ENV=local
      - APP_KEY=base64:qePhv2BwXyo1nAWdVcAVRzIPbbblpXZsimE7UYnr5Yw=
      - DB_CONNECTION=sqlite
      - DB_DATABASE=/var/www/html/database/database.sqlite
    volumes:
      - .:/var/www/html
      - ./database:/var/www/html/database
    ports:
      - "8000:80"
  